[build]
  # Build command with optimization
  command = "npm run build"

  # Directory to publish (Vite builds to 'dist' by default)
  publish = "dist"

  # Build processing settings
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':!README.md' ':!docs/'"

[build.environment]
  # Node.js version (LTS)
  NODE_VERSION = "20"

  # Production environment
  NODE_ENV = "production"

  # Build optimizations
  GENERATE_SOURCEMAP = "false"
  CI = "true"

  # Memory optimization for large builds
  NODE_OPTIONS = "--max-old-space-size=4096"

  # Supabase configuration (temporary - move to dashboard for security)
  VITE_SUPABASE_URL = "https://eekajmfvqntbloqgizwk.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVla2FqbWZ2cW50YmxvcWdpendrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMjk5NTIsImV4cCI6MjA2MTgwNTk1Mn0.HfR6KwhaWCRcrlavKiY0XUo_SXX2epQNrCV4sya2kl4"
  VITE_SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVla2FqbWZ2cW50YmxvcWdpendrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NjIyOTk1MiwiZXhwIjoyMDYxODA1OTUyfQ.IQgAFxPi-0Oy9KX4MVFXsoTymxSVCzgPNIw76Um9UCQ"

# Context-specific builds
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build:dev"

[context.branch-deploy]
  command = "npm run build"

# Redirects and rewrites
[[redirects]]
  # API routes (if using Netlify Functions)
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  # Redirect old URLs to new structure
  from = "/dashboard/*"
  to = "/student/:splat"
  status = 301
  force = false

[[redirects]]
  # SPA fallback - must be last
  from = "/*"
  to = "/index.html"
  status = 200

# Enhanced Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy (allow necessary domains)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.supabase.co cdn.gpteng.co; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' *.supabase.co wss://*.supabase.co; frame-ancestors 'none';"

    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # HSTS (HTTP Strict Transport Security)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

    # Permissions Policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"

    # Additional security (simplified)
    Cross-Origin-Opener-Policy = "same-origin"

# Optimized Caching Strategy

# HTML files - no cache (always fresh)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# JavaScript and CSS assets (with hash) - long cache
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Static assets - long cache
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Fonts - long cache
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Images - long cache
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# PWA files - short cache
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Performance optimizations
[[headers]]
  for = "/index.html"
  [headers.values]
    # Preconnect to external domains
    Link = '''<https://fonts.googleapis.com>; rel=preconnect,
              <https://fonts.gstatic.com>; rel=preconnect; crossorigin,
              <https://eekajmfvqntbloqgizwk.supabase.co>; rel=preconnect'''

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Dev server settings
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  autoLaunch = false

  # Environment variables for development
  [dev.env]
    NODE_ENV = "development"

# Build plugins (commented out - install manually if needed)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"
#
#   [plugins.inputs]
#     output_path = "lighthouse"
#
# [[plugins]]
#   package = "netlify-plugin-submit-sitemap"
#
#   [plugins.inputs]
#     baseUrl = "https://mmu-digital-campus.netlify.app"
#     sitemapPath = "/sitemap.xml"
#     providers = [
#       "google",
#       "bing"
#     ]
