// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://eekajmfvqntbloqgizwk.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVla2FqbWZ2cW50YmxvcWdpendrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMjk5NTIsImV4cCI6MjA2MTgwNTk1Mn0.HfR6KwhaWCRcrlavKiY0XUo_SXX2epQNrCV4sya2kl4';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Missing Supabase environment variables!');
  console.error('Required: VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY');
  console.error('Please configure these in Netlify dashboard: Site Settings → Environment Variables');
  throw new Error('Supabase configuration missing. Check environment variables.');
}

if (import.meta.env.DEV) {
  console.log('✅ Supabase client initialized successfully');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);